apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hexagonal-api
  template:
    metadata:
      labels:
        app: hexagonal-api
    spec:
      containers:
      - name: adapter-rest
        image: sam0999/mis-patitas-backend:v1.7.1
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: hexagonal-config
